variable "autogenerated" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "allowaccess" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_identification" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_action_on_extender" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_alert_interfaces" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      name = string
    }
  ))
  default = []
}

variable "fail_alert_method" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_detect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_detect_option" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "interface" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "mtu" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "mtu_override" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "name" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "remote_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "role" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "tcp_mss" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "vdom" {
  description = "(required)"
  type        = string
}

variable "vlanid" {
  description = "(optional) VLAN ID (1 - 4094)"
  type        = number
  default     = null
}
